<a href="https://colab.research.google.com/github/zweibo/ML-Coding/blob/master/TF_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import absolute_import, division, print_function

In [0]:
import tensorflow as tf

from tensorflow import Session as sess

In [0]:
tf.version

In [0]:
tf.enable_eager_execution()

In [0]:
tf.executing_eagerly()

True

In [0]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


In [0]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [0]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [0]:
a *2

<tf.Tensor: id=8, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [0]:
print(a * 2)

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [0]:
b = a*2

In [0]:
type(b)

tensorflow.python.framework.ops.EagerTensor

In [0]:
import numpy as np

In [0]:
c = np.multiply(a, b)

In [0]:
type(c)

numpy.ndarray

In [0]:
print(a*b)

tf.Tensor(
[[ 2  8]
 [18 32]], shape=(2, 2), dtype=int32)


In [0]:
c

array([[ 2,  8],
       [18, 32]], dtype=int32)

In [0]:
a.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [0]:
a.consumers

<bound method _EagerTensorBase.consumers of <tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>>

In [0]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [0]:
c = tf.matmul(a, b)

In [0]:
print(c)

tf.Tensor(
[[14 20]
 [30 44]], shape=(2, 2), dtype=int32)


In [0]:
a = a * 3

In [0]:
a

<tf.Tensor: id=25, shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>

In [0]:
a[2] = ['a', 'e']

TypeError: ignored

In [0]:
d = tf.constant(['a', 'h'])

In [0]:
d

<tf.Tensor: id=36, shape=(2,), dtype=string, numpy=array([b'a', b'h'], dtype=object)>

In [0]:
class MNISTModel(tf.keras.Model):
  def __init__(self):
    super(MNISTModel, self).__init__()
    self.dense1 = tf.keras.layers.Dense(units=10)
    self.dense2 = tf.keras.layers.Dense(units=10)

  def call(self, input):
    """Run the model."""
    result = self.dense1(input)
    result = self.dense2(result)
    result = self.dense2(result)  # reuse variables from dense2 layer
    return result

model = MNISTModel()

In [0]:
type(model)

__main__.MNISTModel

# **TF.data import practice**



In [0]:
test_dataset = tf.data.Dataset.from_tensors(a)

In [0]:
test_dataset

<TensorDataset shapes: (2, 2), types: tf.int32>

In [0]:
print(test_dataset)

<TensorDataset shapes: (2, 2), types: tf.int32>


In [0]:
type(test_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [0]:
test_dataset.

<WindowDataset shapes: <tensorflow.python.data.ops.dataset_ops._NestedDatasetComponent object at 0x7f5435c92e80>, types: <tensorflow.python.data.ops.dataset_ops._NestedDatasetComponent object at 0x7f5435c92e80>>

In [0]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random_uniform([4, 10]))
print(dataset1.output_types)  # ==> "tf.float32"
print(dataset1.output_shapes)  # ==> "(10,)"

<dtype: 'float32'>
(10,)


In [0]:
tf.random_uniform([4, 10])

<tf.Tensor: id=64, shape=(4, 10), dtype=float32, numpy=
array([[0.05787456, 0.25683415, 0.9932033 , 0.12471223, 0.7863964 ,
        0.2877823 , 0.57228756, 0.9839413 , 0.8404821 , 0.16067874],
       [0.46652138, 0.6265391 , 0.20048857, 0.7635275 , 0.5741178 ,
        0.5998968 , 0.21601522, 0.84386814, 0.8146161 , 0.48145103],
       [0.63482714, 0.07140076, 0.27678442, 0.23641074, 0.04743326,
        0.03044355, 0.04237282, 0.6130148 , 0.8071662 , 0.68787277],
       [0.45841217, 0.79950213, 0.1845727 , 0.11186337, 0.30321813,
        0.6041831 , 0.07993722, 0.3602996 , 0.88574684, 0.09164298]],
      dtype=float32)>

In [0]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random_uniform([4]),
    tf.random_uniform([4, 100], maxval=100, dtype=tf.int32)))
print(dataset2.output_types)  # ==> "(tf.float32, tf.int32)"
print(dataset2.output_shapes)

(tf.float32, tf.int32)
(TensorShape([]), TensorShape([Dimension(100)]))


In [0]:
tf.random_uniform([4, 10], maxval=100, dtype=tf.int32)

<tf.Tensor: id=88, shape=(4, 10), dtype=int32, numpy=
array([[ 2, 54, 64, 51,  6, 15, 13,  4, 58, 74],
       [98, 51, 52, 22, 83, 92, 39, 39, 14, 36],
       [88, 79, 19, 55,  0, 23, 18, 48,  9, 46],
       [86,  4, 78, 82,  2, 95, 54,  2, 10, 98]], dtype=int32)>

In [0]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
print(dataset3.output_types)  # ==> (tf.float32, (tf.float32, tf.int32))
print(dataset3.output_shapes)  # ==> "(10, ((), (100,)))"

(tf.float32, (tf.float32, tf.int32))
(TensorShape([Dimension(10)]), (TensorShape([]), TensorShape([Dimension(100)])))


In [0]:
dataset = tf.data.Dataset.from_tensor_slices(
   {"a": tf.random_uniform([4]),
    "b": tf.random_uniform([4, 100], maxval=100, dtype=tf.int32)})
print(dataset.output_types)  # ==> "{'a': tf.float32, 'b': tf.int32}"
print(dataset.output_shapes)  # ==> "{'a': (), 'b': (100,)}"

{'a': tf.float32, 'b': tf.int32}
{'a': TensorShape([]), 'b': TensorShape([Dimension(100)])}


In [0]:
tup =    {"a": tf.random_uniform([4]),
    "b": tf.random_uniform([4, 100], maxval=100, dtype=tf.int32)}

In [0]:
type(tup)

dict

In [0]:
dataset1 = dataset1.map(lambda x: x + 1)

In [0]:
type(dataset1)

tensorflow.python.data.ops.dataset_ops.MapDataset

##**Creating an iterator- from here down**

In [0]:
dataset = tf.data.Dataset.range(100)


In [0]:
print (dataset2)

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>


In [0]:
filenames = ["zxnchb/kaggle/titanic/tit_test.csv"]
record_defaults = [tf.string, tf.float32, tf.float32]  # Eight required float columns
dataset = tf.contrib.data.CsvDataset(filenames, record_defaults)

In [0]:
dataset

<CsvDataset shapes: ((), (), ()), types: (tf.string, tf.float32, tf.float32)>

In [0]:
tf.print(dataset)

In [0]:
from google.colab import files
uploaded = files.upload("/Users/zxnchb/kaggle/titanic/tit_test.csv")

TypeError: ignored

In [0]:
iterator = dataset.make_one_shot_iterator()
for x, y, z in iterator:
  print(x, y, z)

NotFoundError: ignored